### ISSUE TITLE
Shikimori (Шикимори) Integration

### ISSUE THREAD

**Issue by nattadasu** [infanf/myanili#32]
[Shikimori \(Шикимори\)](https://shikimori.one) is one of local anime tracking service that targeted to Russian users, similar to Annict with Japanese _market_. 

One thing I noticed during creating [my personal project](https://github.com/nattadasu/ryuuganime-db) is, Shikimori shares almost 100% of entries database and ID with MyAnimeList , so that make me think if MyAni.li can integrate with it seamlessly just by using MAL entry ID for Shikimori. I haven't found an entry with different ID with MAL till date.

However, there's some entries use unique prefixes like `x`, `y`, and `z`. If user tried to access prefixed entry without prefix, it will redirected to newer/prefixed one.

Below is a list of ID that I noticed:

| Title | Type | MyAnimeList ID | Shikimori ID | Uses Prefix |
| ----- | :--: | :------------: | :----------: | :---------: |
| Gintama° | TV Series | [`28977`](http://myanimelist.net/anime/28977) | [`z28977`](https://shikimori.one/animes/z28977) | :heavy_check_mark: |
| Tensai Ouji no Akaji Kokka Saisei Jutsu | TV Series | [`47159`](http://myanimelist.net/anime/47159) | [`47159`](https://shikimori.one/animes/47159) | :x: |
| Kaguya-sama wa Kokurasetai?: Tensai-tachi no Renai Zunousen | TV Series | [`40591`](http://myanimelist.net/anime/40591) | [`40591`](https://shikimori.one/animes/40591) | :x:
| Genjitsu Shugi Yuusha no Oukoku Saikenki | Light Novel | [`107884`](http://myanimelist.net/manga/107884) | [`107884`](https://shikimori.one/ranobe/107884) | :x: |
| Koe no Katachi | Movie | [`28851`](http://myanimelist.net/anime/28851) | [`y28851`](https://shikimori.one/animes/y28851) | :heavy_check_mark: |
| Kimi no Suizou wo Tabetai | Movie | [`36098`](http://myanimelist.net/anime/36098) | [`z36098`](https://shikimori.one/animes/z36098) | :heavy_check_mark: |
| Violet Evergarden Movie | Movie | [`37987`](http://myanimelist.net/anime/37987) | [`37987`](https://shikimori.one/animes/37987) | :x: |

API Documentation can be accessed from here: https://shikimori.one/api/doc

FYI, language of the site can be changed through Settings page after logged in. I don't know why they did not make a separate option that can be accessed by foreign customer without logging in.

**Comment by infanf** [comment]
@nattadasu I'll look into it tomorrow, have to wait a day after registration before I can create an app for oauth

**Comment by infanf** [comment]
issue will be closed and feature not implemented. I'm not interested in supporting a Russian site.

**Comment by nattadasu** [comment]
Ah, alright. Thanks for trying.

**Comment by infanf** [comment]
I'm havin' the suspition that shikimori is basically just a russian frontend for MAL 🤔 every ID and rating I've checked is basically identical on both sites
