### ISSUE TITLE
Add Dropdown Feature for Start and End Date

### ISSUE THREAD

**Issue by nattadasu** [infanf/myanili#56]
Add a feature where user can add both reading/watching start date and end date as MyAnimeList did not automatically add the date when user starts the title or finished, or when Kitsu added date based on UTC 0 thus sometimes resulting in inaccurate date.

Preferably the webapp will configure date automatically when starting or completing the title based on device local time. 

AniList does not have such issue as they used user's timezone as reference and add the start and/or end date while updating.

**Comment by infanf** [comment]
I like the idea. What's your opinion on dropping series regarding finish date? Anilist keeps it empty when you drop a series but maybe you'd want to document when you dropped it.

**Comment by infanf** [comment]
Change should be live in a few minutes.
Finish date is currently only set when you finish a series. dropped can be added later

**Comment by nattadasu** [comment]
> I like the idea. What's your opinion on dropping series regarding finish date? Anilist keeps it empty when you drop a series but maybe you'd want to document when you dropped it.

Well, as I observed on Kitsu via official app and Taiga, they'll just leave it blank by default, but user still able to add it manually later 👀
