### ISSUE TITLE
[BUG] LiveChart: Unreleased title has invalid year

### ISSUE THREAD

**Issue by nattadasu** [infanf/myanili#66]
I found a bug while adding [Wind Breaker](https://myani.li/#/anime/details/54900) to my list where if the show is TBA/Unreleased, MyAniLi will show wrong year `(2021)` whew in [LiveChart](https://www.livechart.me/anime/11916), there is literally 0 mention to `2021`, expected behavior should be either `TBA` or leave blank.

![MyAniLi](https://user-images.githubusercontent.com/49780229/228951303-c0758b1b-bc68-4fa1-8df2-f59b8dcf5189.png)

![LiveChart](https://user-images.githubusercontent.com/49780229/228951951-0c3362ac-1dd3-4dbd-adca-8418b7a26a90.png)

**Comment by infanf** [comment]
Thanks for the report. Their API always reports a start date. Had to check for the "precision" attribute.
![image](https://user-images.githubusercontent.com/8826710/229376574-879f5d35-d0a4-4951-9876-e034d7c57bce.png)
