### ISSUE TITLE
"Translate" different score types/systems

### ISSUE THREAD

**Issue by K0-RR** [infanf/myanili#74]
Currently:
![image](https://github.com/infanf/myanili/assets/43277609/c5cb845e-6e96-45be-9024-a7be85a1c7e9)

After the change:
![image](https://github.com/infanf/myanili/assets/43277609/48cbf462-073f-4c82-85ad-7a8bb6f1e2ec)

This would require multiplying the scores from `MAL, SIMKL, AniSearch, LiveChart, and ANN` 10 times.
Also, AniSearch uses a scale from 1 to 5 so it needs to also be multiplied by 2 (or simply once, by 20)

**Comment by infanf** [comment]
I might add this as an option to set according to your preference. The values are already there because I use a unified score to calculate the average score you see under the poster
