### ISSUE TITLE
Kitsu.io domain is expired

### ISSUE THREAD

**Issue by nattadasu** [infanf/myanili#87]
Seems the domain should be updated to kitsu.app, for now image/cdn links were broken in-app and possibly affected on api result as well. 

![Screenshot_2024-08-11-12-19-46-800_com.discord.jpg](https://github.com/user-attachments/assets/4d61ff4a-5997-4523-b678-719ab6311ac6)

**Comment by infanf** [comment]
@nattadasu thanks for pointing this out
